# YUNSH OS logrotate configuration
/var/log/yunsh-network.log
/var/log/yunsh-bluetooth.log
/var/log/yunsh-update.log {
    rotate 4
    weekly
    maxsize 10M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}
